os:
- linux
sudo: false
language: node_js
node_js: stable
env:
  matrix:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="4"
notifications:
  email:
  - themadcreator@themadcreator.com
deploy:
  provider: npm
  email: themadcreator@themadcreator.com
  api_key:
    secure: gOS79jchrCjxN1TM9qJO+TvI5Tb1T4Gyb4y5EDIjdFXtK9m4bhMyy1Pg8eM5GcfZ8qJ0hqQrCiHWrkYAKyaYkxdJtGPn2WYrmo6d0OwLFjjP3Bp1XulN0x8ehNqfSFfsnlpl6Ya31mAlha8NJJ2txlLHxkPetvBXTTRr2q+r7pEsrnwDjzu6ZXW9hSJxTg32ACUftLdQbv9RzXrfYqzHmzrQcOuCQOxiyTOFyTYsB7c/XRLAG4S657w6fn2Gt0NWgmqxCfAaMo6NR3cc9m68U5BKULETi67YTBLMCryKDovUT1AIeCNzoL/kqRd8D14dVKA1xxEzNDTmxQcST/rym+YYzQji2Lw+ujpnIOcz55w/4fqx2pxiDa8p876R5HztO9PEWAhgK/HM1KopT+7w06yCSlxtZe30L4C1sqlqWv655chCginJP0huLkqlnOCYnY4GfPvRjfWyUgU+j1xk3HEbup4JqwBOQTOIIwoX9B5y68SNk4HC/8SRxOahrYKAsSR3qhpTeot2fjC45G03q7TKg/3v+kvYgcWInng477EzylIR5wncHTD7NvwXBSGEeKfVN2Pqwih7hlfQhNIcyUjdnVUhgbKuAItqI16SDK5FIn4HgubOYLjLhzxi9bWvVQB1XvuBguW/VHON9QzZO3+r+tc/P6hBWFcPZ2r7gjM=
  on:
    tags: true
