os:
  - linux
sudo: false
language: node_js
node_js: stable
env:
  matrix:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="4"
notifications:
  email:
    - themadcreator@themadcreator.com