os:
- linux
sudo: false
language: node_js
node_js: stable
env:
  matrix:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="4"
notifications:
  email:
  - themadcreator@themadcreator.com
deploy:
  provider: npm
  email: themadcreator@themadcreator.com
  api_key:
    secure: qrEYoDLhwvtix4sel95A7iqUqUwnJdjJ8KsWqvNnZj+KKUS2t4qTbe6zTr+qDbkCjOTwDze2oOWMNyIUzbDRRk4McNtRd4g4MDbic6yCQePmpij/SUUBKI09eZPj+wR8pXpcMJqcrZ61Y1b+eqxm3a/1sMpoKOl8ruEBLOEjmLm2903cHHA81wEhf/l3pKhQCcWvLnwzz2PvVwlgWjvialgBrqvtgOnSXmz3QBX48A5GlcKO9FceMv2PgZgleGeIlLwQIthzBCFaFWNvkJOF0ZB87jRrWhdQ8g9pdc2fJSRZPqWK3VRSrxB1Tuudbc4pbo8sIOZ1GdJTHGfOku539s5lu94C++ioTmAGoDj9Q+LjY9D0Y1aZ/LeYenfgckqDQSbvWiOIRKC3kDz9k0j3dGFMtHIKBhofef3N1idfd0bPnX3zlPPBGz0MRKhgbkjpuS3pubfC1ucTaCh9jgE4FWabPJh4pV3hgdiFjEeQyFMRt7K35SMsxRkRngVqCwHRFYsCJIY/gXHnlHuV81KJoJcXlrAeEL+AyAMbW8YQ3rx7kSDyIi+UgNTybSSfQYB+agvj7wImXLYP1rq92/7Xohuk9ljjhuZrL3jr3/C/GrsWZ2oj6ZKoDl9LQzL1fk6Ue5Kn2E97VsbENsBwBzbkr25xPoP2TssTQ9D8q7K7YRc=
  on:
    tags: true
